typedef enum {
  _READ_INFOR_MODULE = 0x4E,
  _RUNNING_INFOR_MODULE = 0x4F,
  _SET_MODULE_OPERATION = 0x4D,
  _SET_FLATFORM_INFOR = 0x50,
  _SYNC_TIMER_LIST = 0x13,
  _MODIFY_TIMER = 0x14,
  _SYNC_TIMESTAMP = 0x06,
  _SET_COMMAND1 = 0x07,
  _SET_COMMAND2 = 0x17,
  _GET_DEVICE_TIMER = 0x08,
  _DEVICE_RPT_RUNNING_STATUS = 0x21,
  _BAT_RPT_RUNNING_STATUS = 0x22,
  _DEVICE_RPT_RUNNING_STATUS2 = 0x23,
  _QUERY_COMMAND = 0x09,
  _RTN_COMMAND = 0x24,
  _SET_MODULE_BRDCAST_NAME = 0x4C,
  _SET_BLUETOOTH_PAIR_PW = 0x4B,
  _SET_DEVICE_TYPE = 0x4A,
  _VERIFY_BLUETOOTH_PAIR_PW = 0x48,
  _QUERY_PW_STATUS_INFOR = 0x47,
  _SET_WIFI_ACC_PW = 0x46,
  _QUERY_DEVICE_PLATFORM = 0x51,
} CODE;
enum 
{
  CONNECTED,
  DISCONNECTED,
} SERIAL_STATUS;
