typedef enum 
{
    _RESTORE_FACTORY_RESET = 0x01,
    _MODULE_RESET = 0x02,
    _ON_CLICK_NETWORK_CONFIG =0x03,
    _AP_NETWORK_CONFIG = 0x04,
    _FACTORY_TEST_MODE =0x05,
    _DISCONNECT_BLUETOOTH= 0x06,
    _NO_OPERATION = 0x07,
} FC_SET_DEVICE_MODULE;